<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        .container{
            display: flex;

        }
        .container>div{
            width: 30%;
            background-color: cadetblue;
            margin: 10px;
            display: flex;
        }

    </style>
</head>
<body>
<div class="container">
    <div>
        <input type="text" id="country" placeholder="Search country...">
        <table>
            <tr></tr>
        </table>
    </div>
    <div>sdf</div>

</div>

</body>
</html>